[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling"
position = "after"
match_indent = true
payload = '''
  self.chips = self.chips * G.GAME.paperback.blind_multiplier
'''

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling"
position = "after"
match_indent = true
payload = '''
  blind_amt = blind_amt * G.GAME.paperback.blind_multiplier
'''