[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:get_chip_mult()"
position = "after"
match_indent = true
payload = '''
if self.ability.effect == "Mult Card" then
  print("Scoring Mult")
  if SMODS.find_card('j_paperback_boundary_of_death') then
    if pseudorandom('bod_mult') < G.GAME.probabilities.normal/4 then
    print("BOD ACTIVE")
      return 50
  end
end
'''
