
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# This is merely a visual modification, so that the boss shows the multiplied amount
# Currently it doesn't immediately update the existing text, and it only works
# when the UI is recreated
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling"
position = "after"
match_indent = true
payload = '''
local paperback_scaling = G.GAME and G.GAME.round_resets.paperback_extra_boss_scaling
if paperback_scaling and blind_choice.config.boss then
  blind_amt = blind_amt * paperback_scaling
end
'''

# The actual score is modified when the blind is selected
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling"
position = "after"
match_indent = true
payload = '''
local paperback_scaling = G.GAME and G.GAME.round_resets.paperback_extra_boss_scaling
if paperback_scaling and self.config.blind.boss then
  self.chips = self.chips * paperback_scaling
end
'''
