[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# We add the mod badge to our Paperclips
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "badges.mod_set = nil"
position = "before"
match_indent = true
payload = '''
if PB_UTIL and card and card.ability then
  local key = PB_UTIL.has_paperclip(card)
  if key then
    SMODS.create_mod_badges(SMODS.Stickers[key], badges)
  end
end
'''
