[manifest]
version = "1.0.0"
dump_lua = true
priority = -20

# eval_card()
# Debuffed held-in-hand cards' "debuffed" text works
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''for _, key in ipairs(SMODS.custom_debuff_handling) do if card.config.center_key == key then vanilla_debuff_handling = true; break end end'''
position = 'after'
match_indent = true
payload = '''
if context.paperback and context.paperback.soaked then vanilla_debuff_handling = true end
'''